version: '3.1'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: taglist
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - "3306:3306"
  server:
    build: .
    restart: always
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: taglist
      DB_USERNAME: dev
      DB_PASSWORD: dev
    ports:
      - "3000:3000"